version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/src/app
      - ./tests:/src/tests
      - ./pytest.ini:/src/pytest.ini
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy

  worker:
    build: .
    command: celery -A app.tasks.celery_app.celery worker --loglevel=info
    volumes:
      - ./app:/src/app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy

  beat:
    build: .
    command: celery -A app.tasks.celery_app.celery beat --loglevel=info
    volumes:
      - ./app:/src/app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
